### PR TITLE
Report better error messages

### LINKED ISSUE #45: Parser should return nice syntax error messages

### PR DESCRIPTION
**Pull request by thejoelw**
Closes #45

### CODE REVIEW

**Comment by dane-johnson** [comment]
What does this PR do?

**Comment by dane-johnson** [comment]
I suggest editing this description to match the new PR template. This seems vague and undocumented.

**Review by Hopding — APPROVED** [review]
I'm fine with merging this. However, I do think that in the future, we should have more detailed stories and PRs in this repo. Similar (probably identical) to the templates we are using in the UI and Lambda repos.

**Review by thebho — APPROVED** [review]

**Comment by thejoelw** [comment]
Opened #58 to document

**Pull request merged**
